[tool.mypy]
plugins = [
    "pydantic.mypy",
]
python_version = '3.10'
files = ['**/*.py',]
exclude = [
    '^venv/',
    '\\.git/',
    '\\.mypy/'
]
warn_redundant_casts = true
warn_unused_ignores = true
show_error_codes = true
namespace_packages = true

# Silint "type import errors" as our 3rd-party libs does not have types
# Check: https://mypy.readthedocs.io/en/latest/config_file.html#import-discovery
follow_imports = 'silent'
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = []
